# Generated by Django 2.2.15 on 2020-09-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='img',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
